export const LOGIN_ROUTE = '/login'
export const ANIME_SEARCH = '/search'
export const ANIME_LIST_ROUTE = '/'
export const ANIME_PAGE_ROUTE = '/anime/:animeId'
export const FAVOURITE_ROUTE = '/favorite'
export const FAVOURITE_PAGE_ROUTE = '/favorite/:animeId'